In [1]:
import numpy as np

# Generating Data

In [50]:
a = np.arange(5)
b = np.arange(5,10)
c = np.arange(10,100,10)
print "a, b, and c are", a, b, c

a, b, and c are [0 1 2 3 4] [5 6 7 8 9] [10 20 30 40 50 60 70 80 90]


In [57]:
a = np.linspace(0,5) # n points between i and j, default is 50
print "a is", a
b = np.linspace(-5,5,11) # points can be ± and floating
print "b is", b

a is [ 0.          0.10204082  0.20408163  0.30612245  0.40816327  0.51020408
  0.6122449   0.71428571  0.81632653  0.91836735  1.02040816  1.12244898
  1.2244898   1.32653061  1.42857143  1.53061224  1.63265306  1.73469388
  1.83673469  1.93877551  2.04081633  2.14285714  2.24489796  2.34693878
  2.44897959  2.55102041  2.65306122  2.75510204  2.85714286  2.95918367
  3.06122449  3.16326531  3.26530612  3.36734694  3.46938776  3.57142857
  3.67346939  3.7755102   3.87755102  3.97959184  4.08163265  4.18367347
  4.28571429  4.3877551   4.48979592  4.59183673  4.69387755  4.79591837
  4.89795918  5.        ]
b is [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]


In [104]:
baseline = np.zeros(5) # 5 zeros
ones = np.ones(5) # 5 ones

def f(x,y):   # some shape
    return x*y

slope = -ones*2 + [f(i,i) for i in range(5)]

print slope
print baseline
print "average change from baseline", (baseline - slope).mean()

[ -2.  -1.   2.   7.  14.]
[ 0.  0.  0.  0.  0.]
average change from baseline -4.0


### Random numbers

In [63]:
a = np.random.rand(5) # 5 random numbers between 0 and 1
b = np.random.rand(2,3) # 6 random numbers in a matrix
print "a and b are", a, b

a and b are [ 0.8108409   0.37323045  0.01690656  0.51114643  0.0168598 ] [[ 0.07642873  0.55111452  0.26693922]
 [ 0.43481018  0.40193312  0.81175921]]


In [66]:
mean = 5
sigma = 2
gauss = np.random.normal(mean, sigma, 5) # generate 5 random numbers from a gaussian
print gauss

[ 5.58064441  5.38424948  4.73223765  6.4968407   6.60631411]


In [71]:
uniform = np.random.uniform(10,15,5) # generate 5 random numbers from a uniform distribution between i, j
print uniform

[ 13.46921423  12.54341688  13.38811623  10.44393864  14.72504023]


In [95]:
gauss = np.random.normal(mean, sigma, 1000) # lots of data
sample = np.random.choice(gauss, 5) # 5 random points from the data
print sample

[ 3.39475603  6.18404346  8.14726529  7.46768919  4.05358013]


# Statistics and sumarising data

In [86]:
data = np.random.normal(0,2,100) # lots of data
highest = data.max()
lowest = data.min()
print highest, lowest

6.02889291852 -4.4055362721


In [88]:
print data.mean(), np.median(data), data.var(), data.std()

0.010832374706 0.143203458373 3.6766754897 1.91746590314


or histogramming

In [94]:
hist, bins = np.histogram(data, bins = np.linspace(data.min(), data.max(), 10))
print hist 

[ 4  9 26 15 24 12  7  2  1]


There are some things numpy can't do so easily...

In [96]:
from scipy.stats import norm

In [99]:
mu, sigma = norm.fit(data)
print mu, sigma

0.010832374706 1.91746590314
